#!/usr/bin/env bash

_wifi() {
  local current="${COMP_WORDS[COMP_CWORD]}"

  if [ "$COMP_CWORD" -eq "1" ]; then
    COMPREPLY+=($(compgen -W "--scan" -- "$current"))
  fi

  if [ "$COMP_CWORD" = "1" -o \( "$COMP_CWORD" = "2" -a "${COMP_WORDS[COMP_CWORD]}" = "--" \) ]; then
    local prefix="${PASSWORD_STORE_DIR:-$HOME/.password-store/}wifi/"

    items=($(compgen -f ${prefix}$current))
    for item in ${items[@]}; do
      item="${item%.gpg}"
      COMPREPLY+=(${item#$prefix})
    done
  fi
}

complete -F _wifi wifi
