#!/usr/bin/env bash

WIFI_IF="${WIFI_IF:-wlan0}"
WIFI_CFG="${WIFI_CFG:-/etc/network/interfaces.d/wifi}"

wifi_connect() {
  local wpa_ssid="$1"
  local wpa_psk=$(wpa_passphrase "$1" "$(pass "wifi/$1")" |
    grep "[^#]psk=" | cut -d= -f2)

  sudo tee "$WIFI_CFG" > /dev/null <<EOF
allow-hotplug $WIFI_IF
iface $WIFI_IF inet dhcp
  wpa-ssid "$wpa_ssid"
  wpa-psk $wpa_psk
EOF

  sudo ifdown "$WIFI_IF"
  sudo ifup "$WIFI_IF"
}

wifi_scan() {
  sudo iwlist "$WIFI_IF" scan | grep -w ESSID | cut -d: -f2 | tr -d \" | grep -v '^\\x00$' | sort -u
}

case "$1" in
  -s|--scan)
    shift
    wifi_scan
    ;;
  --)
    shift
    wifi_connect "$1"
    ;;
  *)
    wifi_connect "$1"
    ;;
esac
